secret_path         = "../secret.ini"
region              = "us-east-2"
private_key_path    = "../ssh_key.pem"
ec2_avail_zone      = "us-east-2a"
author_name         = "flavien"
main_dir            = "../"
